import json

# 英雄英文名与ID映射（按Dota 2客户端顺序，大约126位）
# 来源：Valve Dota2 WebAPI（简化版，不含空格）
hero_list = [
    (1, "antimage"),
    (2, "axe"),
    (3, "bane"),
    (4, "bloodseeker"),
    (5, "crystal_maiden"),
    (6, "drow_ranger"),
    (7, "earthshaker"),
    (8, "juggernaut"),
    (9, "mirana"),
    (10, "morphling"),
    (11, "nevermore"),  # Shadow Fiend
    (12, "phantom_lancer"),
    (13, "puck"),
    (14, "pudge"),
    (15, "razor"),
    (16, "sand_king"),
    (17, "storm_spirit"),
    (18, "sven"),
    (19, "tiny"),
    (20, "vengefulspirit"),
    (21, "windrunner"),
    (22, "zeus"),
    (23, "kunkka"),
    (25, "lina"),
    (26, "lion"),
    (27, "shadow_shaman"),
    (28, "slardar"),
    (29, "tidehunter"),
    (30, "witch_doctor"),
    (31, "lich"),
    (32, "riki"),
    (33, "enigma"),
    (34, "tinker"),
    (35, "sniper"),
    (36, "necrolyte"),
    (37, "warlock"),
    (38, "beastmaster"),
    (39, "queenofpain"),
    (40, "venomancer"),
    (41, "faceless_void"),
    (42, "skeleton_king"),  # Wraith King
    (43, "death_prophet"),
    (44, "phantom_assassin"),
    (45, "pugna"),
    (46, "templar_assassin"),
    (47, "viper"),
    (48, "luna"),
    (49, "dragon_knight"),
    (50, "dazzle"),
    (51, "rattletrap"),  # Clockwerk
    (52, "leshrac"),
    (53, "furion"),  # Nature's Prophet
    (54, "life_stealer"),
    (55, "dark_seer"),
    (56, "clinkz"),
    (57, "omniknight"),
    (58, "enchantress"),
    (59, "huskar"),
    (60, "night_stalker"),
    (61, "broodmother"),
    (62, "bounty_hunter"),
    (63, "weaver"),
    (64, "jakiro"),
    (65, "batrider"),
    (66, "chen"),
    (67, "spectre"),
    (68, "doom_bringer"),
    (69, "ancient_apparition"),
    (70, "ursa"),
    (71, "spirit_breaker"),
    (72, "gyrocopter"),
    (73, "alchemist"),
    (74, "invoker"),
    (75, "silencer"),
    (76, "outworld_destroyer"),
    (77, "lycan"),
    (78, "brewmaster"),
    (79, "shadow_demon"),
    (80, "lone_druid"),
    (81, "chaos_knight"),
    (82, "meepo"),
    (83, "treant"),
    (84, "ogre_magi"),
    (85, "undying"),
    (86, "rubick"),
    (87, "disruptor"),
    (88, "nyx_assassin"),
    (89, "naga_siren"),
    (90, "keeper_of_the_light"),
    (91, "wisp"),  # Io
    (92, "visage"),
    (93, "slark"),
    (94, "medusa"),
    (95, "troll_warlord"),
    (96, "centaur"),
    (97, "magnataur"),
    (98, "shredder"),
    (99, "bristleback"),
    (100, "tusk"),
    (101, "skywrath_mage"),
    (102, "abaddon"),
    (103, "elder_titan"),
    (104, "legion_commander"),
    (105, "techies"),
    (106, "ember_spirit"),
    (107, "earth_spirit"),
    (108, "abyssal_underlord"),
    (109, "terrorblade"),
    (110, "phoenix"),
    (111, "oracle"),
    (112, "winter_wyvern"),
    (113, "arc_warden"),
    (114, "monkey_king"),
    (119, "dark_willow"),
    (120, "pangolier"),
    (121, "grimstroke"),
    (123, "hoodwink"),
    (126, "void_spirit"),
    (128, "snapfire"),
    (129, "mars"),
    (135, "dawnbreaker"),
    (136, "marci"),
    (137, "primal_beast"),
    (138, "muerta")
]

base_url = "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/{}_full.png"

heroes = {}
for hero_id, hero_name in hero_list:
    heroes[hero_name] = {
        "id": hero_id,
        "name": hero_name.replace("_", " ").title(),
        "image": base_url.format(hero_name)
    }

with open("heroes.json", "w", encoding="utf-8") as f:
    json.dump(heroes, f, indent=2, ensure_ascii=False)

print(f"✅ Generated {len(heroes)} heroes.json successfully!")
